# Generated by Django 5.1.2 on 2024-12-19 09:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=50)),
                ('rank', models.PositiveSmallIntegerField(default=9)),
            ],
            options={
                'ordering': ['feature'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('trim', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveSmallIntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], verbose_name='year')),
                ('kilometers', models.PositiveIntegerField(blank=True, null=True)),
                ('exterior_color', models.CharField(blank=True, max_length=100)),
                ('interior_color', models.CharField(blank=True, max_length=100)),
                ('regional_spec', models.CharField(blank=True, choices=[('g', 'GCC Specs'), ('a', 'American Specs'), ('c', 'Canadian Specs'), ('e', 'European Specs'), ('j', 'Japanese Specs'), ('k', 'Korean Specs'), ('n', 'Chinese Specs'), ('x', 'Other')], default='g', max_length=1)),
                ('fuel_type', models.CharField(choices=[('p', 'Petrol'), ('d', 'Diesel'), ('e', 'Electric'), ('h', 'Hybrid')], default='petrol', max_length=1)),
                ('transmission', models.CharField(choices=[('a', 'Automatic'), ('m', 'Manual')], default='automatic', max_length=1)),
                ('body_type', models.CharField(blank=True, choices=[('sv', 'SUV'), ('cp', 'Coupe'), ('se', 'Sedan'), ('xo', 'Crossover'), ('ht', 'Hard Top Convertible'), ('pt', 'Pick Up Truck'), ('hb', 'Hatchback'), ('st', 'Soft Top Convertible'), ('sc', 'Sports Car'), ('vn', 'Van'), ('wg', 'Wagon'), ('ut', 'Utility Truck'), ('oc', 'Other')], max_length=2)),
                ('doors', models.CharField(blank=True, choices=[('2', '2 doors'), ('3', '3 doors'), ('4', '4 doors'), ('5', '5 doors'), ('6', '6+ doors')], max_length=1)),
                ('seating', models.CharField(blank=True, choices=[('2', '2 Seater'), ('4', '4 Seater'), ('5', '5 Seater'), ('6', '6 Seater'), ('7', '7 Seater'), ('8', '8 Seater'), ('9', '9+ Seater')], max_length=1)),
                ('engine_capacity', models.CharField(blank=True, choices=[('a', '0 - 499 cc'), ('b', '500 - 999 cc'), ('c', '1000 - 1499 cc'), ('d', '1500 - 1999 cc'), ('e', '2000 - 2499 cc'), ('f', '2500 - 2999 cc'), ('g', '3000 - 3499 cc'), ('h', '3500 - 3999 cc'), ('i', '4000+ cc'), ('u', 'Unknown')], max_length=1)),
                ('cylinders', models.CharField(blank=True, choices=[('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('8', '8'), ('0', '10'), ('2', '12'), ('u', 'Unknown')], max_length=1)),
                ('horsepower', models.CharField(blank=True, choices=[('a', '0 - 99 HP'), ('b', '100 - 199 HP'), ('c', '200 - 299 HP'), ('d', '300 - 399 HP'), ('e', '400 - 499 HP'), ('f', '500 - 599 HP'), ('g', '600 - 699 HP'), ('h', '700 - 799 HP'), ('i', '800 - 899 HP'), ('j', '900+ HP'), ('u', 'Unknown')], max_length=1)),
                ('steering_side', models.CharField(blank=True, choices=[('l', 'Left Hand'), ('r', 'Right Hand')], default='l', max_length=1)),
                ('warranty', models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No'), ('x', 'Does not apply')], max_length=1)),
                ('selling_price', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('a', 'Active'), ('d', 'Deactive'), ('s', 'Sold')], default='active', max_length=1)),
                ('is_featured', models.BooleanField(default=False)),
                ('slug', models.SlugField(default='', max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=30)),
                ('vin', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('features', models.ManyToManyField(to='app.feature')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/car_images/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_images', to='app.car')),
            ],
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EstateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/estate_images')),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estate_images', to='app.estate')),
            ],
        ),
    ]
