# Generated by Django 5.1.2 on 2024-12-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='age',
            field=models.CharField(max_length=3),
        ),
    ]
